from typing import List, Optional, Protocol, Tuple

from app.models import Category, Material


class BaseDatabase(Protocol):
    backend_name: str

    def is_admin(self, user_id: int) -> bool: ...
    def upsert_group(self, chat_id: int, title: str) -> None: ...
    def list_groups(self) -> List[Tuple[int, str]]: ...
    def upsert_destination(self, category_id: int, chat_id: int, thread_id: int, title: str) -> None: ...
    def get_destination_for_category(self, category_id: int): ...
    def list_categories(self) -> List[Category]: ...
    def get_category(self, category_id: int) -> Optional[Category]: ...
    def get_category_by_name(self, category_name: str) -> Optional[Category]: ...
    def add_material(self, category_id: int, title: str, description: str, link: str, tags: str, file_id: str) -> int: ...
    def list_materials_by_category(self, category_id: int) -> List[Material]: ...
    def get_material(self, material_id: int) -> Optional[Material]: ...
    def search_materials(self, query: str, limit: int = 20) -> List[Material]: ...
    def add_deadline(self, text: str, deadline_date: str) -> None: ...
    def list_deadlines(self): ...
    def mark_deadline_reminded(self, deadline_id: int) -> None: ...
    def get_or_create_user(self, telegram_id: int, username: str, full_name: str, role: str = "student") -> int: ...
    def add_favorite(self, user_id: int, material_id: int) -> None: ...
    def remove_favorite(self, user_id: int, material_id: int) -> None: ...
    def list_favorites(self, user_id: int) -> List[Material]: ...
    def log_material_view(self, user_id: int, material_id: int) -> None: ...
    def log_search(self, user_id: int, query: str, results_count: int) -> None: ...


STARTER_CATEGORIES = [
    ("Объявления", "📢", 1),
    ("Лекции", "📚", 2),
    ("Домашки", "📝", 3),
    ("Материалы", "📂", 4),
    ("Дедлайны", "📅", 5),
    ("Экзамен", "🧠", 6),
    ("Полезные ссылки", "🔗", 7),
]


def row_to_category(row) -> Category:
    return Category(
        category_id=int(row["category_id"]),
        name=str(row["name"]),
        icon=str(row["icon"]),
        sort_order=int(row["sort_order"]),
    )


def row_to_material(row) -> Material:
    return Material(
        material_id=int(row["material_id"]),
        category_id=int(row["category_id"]),
        title=str(row["title"]),
        description=str(row["description"]),
        link=str(row["link"]),
        tags=str(row["tags"]),
        file_id=str(row["file_id"]),
        created_at_iso=str(row["created_at"]),
    )
